version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:

  nginx:
    image: nginx:latest
    depends_on:
      - mailhog
    volumes:
      - ./compose/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      default:
        aliases:
          - dev.mailhog.com

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: squarelet_local_django
    depends_on:
      - postgres
      - mailhog
      - nginx
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      default:
        aliases:
          - dev.squarelet.com

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: squarelet_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: squarelet_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker
    networks:
      default:
        aliases: []

  celerybeat:
    <<: *django
    image: squarelet_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat
    networks:
      default:
        aliases: []
